In [12]:
import pandas as pd

train = pd.read_csv("C:/Users/dell/Downloads/dataset.csv")

In [13]:
train.head()

1    2  3    4  5    6  7    8  9   10   ...    21  22  23  24  25  26  27  \
0  0  111  0  111  0  111  0  111  0  111   ...     0   8   0   8   0   8   0   
1  0  111  0  111  0  111  0  111  0  111   ...     0   8   0   8   0   8   0   
2  0  111  0  111  0  111  0  111  0  111   ...     0   8   0   8   0   8   0   
3  0  111  0  111  0  111  0  111  0  111   ...     0   8   0   8   0   8   0   
4  0  111  0  111  0  111  0  111  0  111   ...     0   8   0   8   0   8   0   

   28  29  target  
0   8   0       0  
1   8   0       0  
2   8   0       0  
3   8   0       0  
4   8   0       0  

[5 rows x 30 columns]

In [14]:
from sklearn.model_selection import train_test_split

train_, test_, train_labels, test_labels = train_test_split(train.drop('target',axis=1),
                                                          train.target,
                                                          test_size=0.33,
                                                          random_state=42)

In [16]:
from sklearn.naive_bayes import GaussianNB

# Initialize our classifier
gnb = GaussianNB()

# Train our classifier
model = gnb.fit(train_, train_labels)

pred_ = model.predict(test_)

In [35]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

print(classification_report(test_labels,pred_))

print(accuracy_score(test_labels,pred_))





             precision    recall  f1-score   support

          0       0.85      0.77      0.81       143
          1       0.86      0.76      0.81       208
          2       0.76      1.00      0.86        79
          3       0.83      0.86      0.85       325

avg / total       0.84      0.83      0.83       755

0.8317880794701987


In [25]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import make_scorer, accuracy_score
from sklearn.model_selection import GridSearchCV

# Choose the type of classifier. 
clf = RandomForestClassifier()

# Choose some parameter combinations to try
parameters = {'n_estimators': [4, 6, 9], 
              'max_features': ['log2', 'sqrt','auto'], 
              'criterion': ['entropy', 'gini'],
              'max_depth': [2, 3, 5, 10], 
              'min_samples_split': [2, 3, 5],
              'min_samples_leaf': [1,5,8]
             }

# Type of scoring used to compare parameter combinations
acc_scorer = make_scorer(accuracy_score)

# Run the grid search
grid_obj = GridSearchCV(clf, parameters, scoring=acc_scorer)
grid_obj = grid_obj.fit(train_, train_labels)

# Set the clf to the best combination of parameters
clf = grid_obj.best_estimator_

clf.fit(train_, train_labels)



RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=5,
            min_weight_fraction_leaf=0.0, n_estimators=9, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [36]:
pred_clf = clf.predict(test_)

print(classification_report(test_labels,pred_clf))

print(accuracy_score(test_labels,pred_clf))

print(confusion_matrix(test_labels,pred_clf))

             precision    recall  f1-score   support

          0       0.99      0.99      0.99       143
          1       0.96      0.97      0.96       208
          2       1.00      1.00      1.00        79
          3       0.98      0.98      0.98       325

avg / total       0.98      0.98      0.98       755

0.9788079470198675
[[141   2   0   0]
 [  1 201   0   6]
 [  0   0  79   0]
 [  0   7   0 318]]


In [38]:
from sklearn.cross_validation import KFold
import numpy as np
X_all = train.drop('target',axis=1)
y_all = train.target

def run_kfold(clf):
    kf = KFold(891, n_folds=10)
    outcomes = []
    fold = 0
    for train_index, test_index in kf:
        fold += 1
        X_train, X_test = X_all.values[train_index], X_all.values[test_index]
        y_train, y_test = y_all.values[train_index], y_all.values[test_index]
        clf.fit(X_train, y_train)
        predictions = clf.predict(X_test)
        accuracy = accuracy_score(y_test, predictions)
        outcomes.append(accuracy)
        print("Fold {0} accuracy: {1}".format(fold, accuracy))     
    mean_outcome = np.mean(outcomes)
    print("Mean Accuracy: {0}".format(mean_outcome)) 

run_kfold(clf)

Fold 1 accuracy: 1.0
Fold 2 accuracy: 1.0
Fold 3 accuracy: 0.9775280898876404
Fold 4 accuracy: 1.0
Fold 5 accuracy: 1.0
Fold 6 accuracy: 1.0
Fold 7 accuracy: 1.0
Fold 8 accuracy: 0.9550561797752809
Fold 9 accuracy: 1.0
Fold 10 accuracy: 1.0
Mean Accuracy: 0.9932584269662922


In [27]:
test = pd.read_csv("C:/Users/dell/Downloads/test.csv")

In [28]:
test.head()

1    2  3    4  5    6  7    8  9   10 ...  20  21  22  23  24  25  26  27  \
0  0  111  0  111  0  111  0  111  0  111 ...  51   0   8   0   8   0   8   0   
1  0  111  0  111  0  111  0  111  0  111 ...  51   0   8   0   8   0   8   0   
2  0  111  0  111  0  111  0  111  0  111 ...  51   0   8   0   8   0   8   0   
3  0  111  0  111  0  111  0  111  0  111 ...  51   0   8   0   8   0   8   0   
4  0  111  0  111  0  111  0  111  0  111 ...  51   0   8   0   8   0   8   0   

   28  29  
0   8   0  
1   8   0  
2   8   0  
3   8   0  
4   8   0  

[5 rows x 29 columns]

In [31]:
test['target'] = clf.predict(test)

In [32]:
test.head()

1    2  3    4  5    6  7    8  9   10   ...    21  22  23  24  25  26  27  \
0  0  111  0  111  0  111  0  111  0  111   ...     0   8   0   8   0   8   0   
1  0  111  0  111  0  111  0  111  0  111   ...     0   8   0   8   0   8   0   
2  0  111  0  111  0  111  0  111  0  111   ...     0   8   0   8   0   8   0   
3  0  111  0  111  0  111  0  111  0  111   ...     0   8   0   8   0   8   0   
4  0  111  0  111  0  111  0  111  0  111   ...     0   8   0   8   0   8   0   

   28  29  target  
0   8   0       0  
1   8   0       0  
2   8   0       0  
3   8   0       0  
4   8   0       0  

[5 rows x 30 columns]

In [33]:
test.to_csv('C:/Users/dell/Downloads/Submission.csv')